blank_issues_enabled: false
contact_links:
    -   name: Discussions
        url: https://github.com/pixel-clover/small-games-godot/discussions
        about: Please ask and answer general questions here
